// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type Currency struct {
	Name         string  `json:"name"`
	Symbol       string  `json:"symbol"`
	ExchangeRate float64 `json:"exchangeRate"`
	Country      string  `json:"country"`
	URL          string  `json:"url"`
	Xpath        string  `json:"xpath"`
}
